/*
 * Picture Perfect
 *
 * Sample API description. You can find more at.
 *
 * API version: 0.1.0
 * Contact: 1raghavmahajan@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Review struct {

	Id int64 `json:"id,omitempty"`

	Rating int32 `json:"rating,omitempty"`

	Time time.Time `json:"time,omitempty"`

	Author *UserLite `json:"author,omitempty"`

	Movie *MovieLite `json:"movie,omitempty"`
}
