/*
 * Picture Perfect
 *
 * Sample API description. You can find more at.
 *
 * API version: 0.1.0
 * Contact: 1raghavmahajan@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Reservation struct {

	Id int64 `json:"id,omitempty"`

	Show *Show `json:"show,omitempty"`

	Time time.Time `json:"time,omitempty"`

	ReservedStatus bool `json:"reservedStatus,omitempty"`

	Paid bool `json:"paid,omitempty"`

	Active bool `json:"active,omitempty"`

	UserId int64 `json:"userId,omitempty"`

	SeatsReserved []Seat `json:"seatsReserved,omitempty"`

	TransactionDetails *ReservationTransactionDetails `json:"transactionDetails,omitempty"`
}
