/*
 * Picture Perfect
 *
 * Sample API description. You can find more at.
 *
 * API version: 0.1.0
 * Contact: 1raghavmahajan@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FilterOptions1 struct {

	MovieId int64 `json:"movieId,omitempty"`

	RegionName string `json:"regionName,omitempty"`

	CineplexId int64 `json:"cineplexId,omitempty"`
}
