/*
 * Picture Perfect
 *
 * Sample API description. You can find more at.
 *
 * API version: 0.1.0
 * Contact: 1raghavmahajan@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Genre string

// List of Genre
const (
	ACTION Genre = "Action"
	ADVENTURE Genre = "Adventure"
	ANIMATION Genre = "Animation"
	COMEDY Genre = "Comedy"
	DRAMA Genre = "Drama"
	HORROR Genre = "Horror"
	SCIFI Genre = "Scifi"
	THRILLER Genre = "Thriller"
	ROMANCE Genre = "Romance"
)
