/*
 * Picture Perfect
 *
 * Sample API description. You can find more at.
 *
 * API version: 0.1.0
 * Contact: 1raghavmahajan@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Body struct {
	// Additional data to pass to server
	AdditionalMetadata string `json:"additionalMetadata,omitempty"`
	// file to upload
	File string `json:"file,omitempty"`
}
