/*
 * Picture Perfect
 *
 * Sample API description. You can find more at.
 *
 * API version: 0.1.0
 * Contact: 1raghavmahajan@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MovieLite struct {

	Id int64 `json:"id,omitempty"`

	Title string `json:"title,omitempty"`

	Language *Language `json:"language,omitempty"`

	Status *MovieStatus `json:"status,omitempty"`

	ReleaseData string `json:"releaseData,omitempty"`

	Genre *Genre `json:"genre,omitempty"`

	Duration int32 `json:"duration,omitempty"`

	Thumbnail string `json:"thumbnail,omitempty"`

	Certificate *Certificate `json:"certificate,omitempty"`

	Category *Category `json:"category,omitempty"`
}
