/*
 * Picture Perfect
 *
 * Sample API description. You can find more at.
 *
 * API version: 0.1.0
 * Contact: 1raghavmahajan@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Category string

// List of Category
const (
	TV_SHOW Category = "TV-Show"
	MOVIE Category = "Movie"
	DOCUMENTARY Category = "Documentary"
	SHORT_FILM Category = "Short-Film"
)
