/*
 * Picture Perfect
 *
 * Sample API description. You can find more at.
 *
 * API version: 0.1.0
 * Contact: 1raghavmahajan@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MovieStatus string

// List of MovieStatus
const (
	IN_THEATRES MovieStatus = "In-Theatres"
	OFF_THEATRES MovieStatus = "Off-Theatres"
	TO_BE_RELEASED MovieStatus = "To-be-Released"
)
