/*
 * Picture Perfect
 *
 * Sample API description. You can find more at.
 *
 * API version: 0.1.0
 * Contact: 1raghavmahajan@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Cineplex struct {

	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Address *Address `json:"address,omitempty"`

	Region *Region `json:"region,omitempty"`

	ContactNo string `json:"contactNo,omitempty"`
}
