/*
 * Picture Perfect
 *
 * Sample API description. You can find more at.
 *
 * API version: 0.1.0
 * Contact: 1raghavmahajan@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserLite struct {

	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	EmailId string `json:"emailId,omitempty"`

	IfVerified bool `json:"ifVerified,omitempty"`

	PhoneNo string `json:"phone_no,omitempty"`

	Role int32 `json:"role,omitempty"`

	Region *Region `json:"region,omitempty"`

	BillingAddress *Address `json:"billingAddress,omitempty"`
}
