/*
 * Picture Perfect
 *
 * Sample API description. You can find more at.
 *
 * API version: 0.1.0
 * Contact: 1raghavmahajan@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Seat struct {

	Row string `json:"row,omitempty"`

	Number int32 `json:"number,omitempty"`

	Auditorium string `json:"auditorium,omitempty"`
}
