/*
 * Picture Perfect
 *
 * Sample API description. You can find more at.
 *
 * API version: 0.1.0
 * Contact: 1raghavmahajan@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Certificate string

// List of Certificate
const (
	U Certificate = "U"
	UA Certificate = "UA"
	A Certificate = "A"
	S Certificate = "S"
)
