/*
 * Picture Perfect
 *
 * Sample API description. You can find more at.
 *
 * API version: 0.1.0
 * Contact: 1raghavmahajan@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Show struct {

	Id int64 `json:"id,omitempty"`

	Capacity int32 `json:"capacity,omitempty"`

	Format *Format `json:"format,omitempty"`

	StartTime time.Time `json:"startTime,omitempty"`

	Movie *MovieLite `json:"movie,omitempty"`

	Cineplex *Cineplex `json:"cineplex,omitempty"`
}
