/*
 * Picture Perfect
 *
 * Sample API description. You can find more at.
 *
 * API version: 0.1.0
 * Contact: 1raghavmahajan@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Language string

// List of Language
const (
	ENGLISH Language = "English"
	HINDI Language = "Hindi"
	MARATHI Language = "Marathi"
	PUNJABI Language = "Punjabi"
	TAMIL Language = "Tamil"
	TELUGU Language = "Telugu"
)
