/*
 * Picture Perfect
 *
 * Sample API description. You can find more at.
 *
 * API version: 0.1.0
 * Contact: 1raghavmahajan@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Format string

// List of Format
const (
	2D_ Format = "2D"
	3D_ Format = "3D"
	4DX_ Format = "4DX"
	IMAX_2_D Format = "IMAX-2D"
	IMAX_3_D Format = "IMAX-3D"
)
