/*
 * Picture Perfect
 *
 * Sample API description. You can find more at.
 *
 * API version: 0.1.0
 * Contact: 1raghavmahajan@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"AddCineplex",
		strings.ToUpper("Post"),
		"/cineplex",
		AddCineplex,
	},

	Route{
		"AddFeaturedToCategory",
		strings.ToUpper("Post"),
		"/movies/featured",
		AddFeaturedToCategory,
	},

	Route{
		"AddMovieToCatalogue",
		strings.ToUpper("Post"),
		"/movies/",
		AddMovieToCatalogue,
	},

	Route{
		"AddRegion",
		strings.ToUpper("Post"),
		"/regions/",
		AddRegion,
	},

	Route{
		"AddShow",
		strings.ToUpper("Post"),
		"/shows/",
		AddShow,
	},

	Route{
		"AddShowToCineplex",
		strings.ToUpper("Post"),
		"/cineplex/{cineplexId}/shows",
		AddShowToCineplex,
	},

	Route{
		"AddShowToMovie",
		strings.ToUpper("Post"),
		"/movies/{movieId}/shows",
		AddShowToMovie,
	},

	Route{
		"DeleteCineplex",
		strings.ToUpper("Delete"),
		"/cineplex/{cineplexId}",
		DeleteCineplex,
	},

	Route{
		"DeleteFeaturedByCategory",
		strings.ToUpper("Delete"),
		"/movies/featured",
		DeleteFeaturedByCategory,
	},

	Route{
		"DeleteMovie",
		strings.ToUpper("Delete"),
		"/movies/{movieId}",
		DeleteMovie,
	},

	Route{
		"DeleteMoviesById",
		strings.ToUpper("Delete"),
		"/movies/",
		DeleteMoviesById,
	},

	Route{
		"DeleteRegion",
		strings.ToUpper("Delete"),
		"/regions/{regionName}",
		DeleteRegion,
	},

	Route{
		"DeleteReview",
		strings.ToUpper("Delete"),
		"/reviews/{reviewId}",
		DeleteReview,
	},

	Route{
		"DeleteReviewsForMovie",
		strings.ToUpper("Delete"),
		"/movies/{movieId}/reviews",
		DeleteReviewsForMovie,
	},

	Route{
		"DeleteReviewsForUser",
		strings.ToUpper("Delete"),
		"/users/{userId}/reviews",
		DeleteReviewsForUser,
	},

	Route{
		"DeleteShow",
		strings.ToUpper("Delete"),
		"/shows/{showId}",
		DeleteShow,
	},

	Route{
		"DeleteShowList",
		strings.ToUpper("Delete"),
		"/shows/",
		DeleteShowList,
	},

	Route{
		"DeleteShowsForCineplex",
		strings.ToUpper("Delete"),
		"/cineplex/{cineplexId}/shows",
		DeleteShowsForCineplex,
	},

	Route{
		"DeleteShowsForMovie",
		strings.ToUpper("Delete"),
		"/movies/{movieId}/shows",
		DeleteShowsForMovie,
	},

	Route{
		"GetAllUsers",
		strings.ToUpper("Get"),
		"/user",
		GetAllUsers,
	},

	Route{
		"SetCineplexDetails",
		strings.ToUpper("Put"),
		"/cineplex/{cineplexId}",
		SetCineplexDetails,
	},

	Route{
		"SetFeaturedByCategory",
		strings.ToUpper("Put"),
		"/movies/featured",
		SetFeaturedByCategory,
	},

	Route{
		"SetMovieDetails",
		strings.ToUpper("Put"),
		"/movies/{movieId}",
		SetMovieDetails,
	},

	Route{
		"SetRegionDetails",
		strings.ToUpper("Put"),
		"/regions/{regionName}",
		SetRegionDetails,
	},

	Route{
		"SetReviewDetails",
		strings.ToUpper("Put"),
		"/reviews/{reviewId}",
		SetReviewDetails,
	},

	Route{
		"SetShowDetails",
		strings.ToUpper("Put"),
		"/shows/{showId}",
		SetShowDetails,
	},

	Route{
		"UpdateCineplexDetails",
		strings.ToUpper("Patch"),
		"/cineplex/{cineplexId}",
		UpdateCineplexDetails,
	},

	Route{
		"UpdateMovieDetails",
		strings.ToUpper("Patch"),
		"/movies/{movieId}",
		UpdateMovieDetails,
	},

	Route{
		"UpdateRegionDetails",
		strings.ToUpper("Patch"),
		"/regions/{regionName}",
		UpdateRegionDetails,
	},

	Route{
		"UpdateReviewDetails",
		strings.ToUpper("Patch"),
		"/reviews/{reviewId}",
		UpdateReviewDetails,
	},

	Route{
		"UpdateShowDetails",
		strings.ToUpper("Patch"),
		"/shows/{showId}",
		UpdateShowDetails,
	},

	Route{
		"UploadMediaToMovie",
		strings.ToUpper("Post"),
		"/movies/{movieId}/upload-image",
		UploadMediaToMovie,
	},

	Route{
		"AddCineplex",
		strings.ToUpper("Post"),
		"/cineplex",
		AddCineplex,
	},

	Route{
		"DeleteCineplex",
		strings.ToUpper("Delete"),
		"/cineplex/{cineplexId}",
		DeleteCineplex,
	},

	Route{
		"GetCineplexDetails",
		strings.ToUpper("Get"),
		"/cineplex/{cineplexId}",
		GetCineplexDetails,
	},

	Route{
		"GetCineplexesInRegion",
		strings.ToUpper("Get"),
		"/cineplex",
		GetCineplexesInRegion,
	},

	Route{
		"SetCineplexDetails",
		strings.ToUpper("Put"),
		"/cineplex/{cineplexId}",
		SetCineplexDetails,
	},

	Route{
		"UpdateCineplexDetails",
		strings.ToUpper("Patch"),
		"/cineplex/{cineplexId}",
		UpdateCineplexDetails,
	},

	Route{
		"CreateUser",
		strings.ToUpper("Post"),
		"/user",
		CreateUser,
	},

	Route{
		"DeleteUser",
		strings.ToUpper("Delete"),
		"/user/{userId}",
		DeleteUser,
	},

	Route{
		"GetAllUsers",
		strings.ToUpper("Get"),
		"/user",
		GetAllUsers,
	},

	Route{
		"GetUser",
		strings.ToUpper("Get"),
		"/user/{userId}",
		GetUser,
	},

	Route{
		"LoginUser",
		strings.ToUpper("Get"),
		"/user/login",
		LoginUser,
	},

	Route{
		"LogoutUser",
		strings.ToUpper("Get"),
		"/user/logout",
		LogoutUser,
	},

	Route{
		"UpdateUser",
		strings.ToUpper("Put"),
		"/user/{userId}",
		UpdateUser,
	},

	Route{
		"AddFeaturedToCategory",
		strings.ToUpper("Post"),
		"/movies/featured",
		AddFeaturedToCategory,
	},

	Route{
		"AddMovieToCatalogue",
		strings.ToUpper("Post"),
		"/movies/",
		AddMovieToCatalogue,
	},

	Route{
		"DeleteFeaturedByCategory",
		strings.ToUpper("Delete"),
		"/movies/featured",
		DeleteFeaturedByCategory,
	},

	Route{
		"DeleteMovie",
		strings.ToUpper("Delete"),
		"/movies/{movieId}",
		DeleteMovie,
	},

	Route{
		"DeleteMoviesById",
		strings.ToUpper("Delete"),
		"/movies/",
		DeleteMoviesById,
	},

	Route{
		"GetMovieCatalogue",
		strings.ToUpper("Get"),
		"/movies/",
		GetMovieCatalogue,
	},

	Route{
		"GetMovieDetails",
		strings.ToUpper("Get"),
		"/movies/{movieId}",
		GetMovieDetails,
	},

	Route{
		"GetTopMoviesByCategory",
		strings.ToUpper("Get"),
		"/movies/featured",
		GetTopMoviesByCategory,
	},

	Route{
		"SetFeaturedByCategory",
		strings.ToUpper("Put"),
		"/movies/featured",
		SetFeaturedByCategory,
	},

	Route{
		"SetMovieDetails",
		strings.ToUpper("Put"),
		"/movies/{movieId}",
		SetMovieDetails,
	},

	Route{
		"UpdateMovieDetails",
		strings.ToUpper("Patch"),
		"/movies/{movieId}",
		UpdateMovieDetails,
	},

	Route{
		"UploadMediaToMovie",
		strings.ToUpper("Post"),
		"/movies/{movieId}/upload-image",
		UploadMediaToMovie,
	},

	Route{
		"GetMoviesInRegion",
		strings.ToUpper("Get"),
		"/region/{regionName}/movies",
		GetMoviesInRegion,
	},

	Route{
		"AddRegion",
		strings.ToUpper("Post"),
		"/regions/",
		AddRegion,
	},

	Route{
		"DeleteRegion",
		strings.ToUpper("Delete"),
		"/regions/{regionName}",
		DeleteRegion,
	},

	Route{
		"GetMoviesInRegion",
		strings.ToUpper("Get"),
		"/region/{regionName}/movies",
		GetMoviesInRegion,
	},

	Route{
		"GetRegionDetails",
		strings.ToUpper("Get"),
		"/regions/{regionName}",
		GetRegionDetails,
	},

	Route{
		"GetRegions",
		strings.ToUpper("Get"),
		"/regions/",
		GetRegions,
	},

	Route{
		"SetRegionDetails",
		strings.ToUpper("Put"),
		"/regions/{regionName}",
		SetRegionDetails,
	},

	Route{
		"UpdateRegionDetails",
		strings.ToUpper("Patch"),
		"/regions/{regionName}",
		UpdateRegionDetails,
	},

	Route{
		"AddReviewToMovie",
		strings.ToUpper("Post"),
		"/movies/{movieId}/reviews",
		AddReviewToMovie,
	},

	Route{
		"DeleteReview",
		strings.ToUpper("Delete"),
		"/reviews/{reviewId}",
		DeleteReview,
	},

	Route{
		"DeleteReviewsForMovie",
		strings.ToUpper("Delete"),
		"/movies/{movieId}/reviews",
		DeleteReviewsForMovie,
	},

	Route{
		"DeleteReviewsForUser",
		strings.ToUpper("Delete"),
		"/users/{userId}/reviews",
		DeleteReviewsForUser,
	},

	Route{
		"GetReviewDetails",
		strings.ToUpper("Get"),
		"/reviews/{reviewId}",
		GetReviewDetails,
	},

	Route{
		"GetReviews",
		strings.ToUpper("Get"),
		"/reviews/",
		GetReviews,
	},

	Route{
		"GetReviewsByMovie",
		strings.ToUpper("Get"),
		"/movies/{movieId}/reviews",
		GetReviewsByMovie,
	},

	Route{
		"GetReviewsByUser",
		strings.ToUpper("Get"),
		"/users/{userId}/reviews",
		GetReviewsByUser,
	},

	Route{
		"SetReviewDetails",
		strings.ToUpper("Put"),
		"/reviews/{reviewId}",
		SetReviewDetails,
	},

	Route{
		"UpdateReviewDetails",
		strings.ToUpper("Patch"),
		"/reviews/{reviewId}",
		UpdateReviewDetails,
	},

	Route{
		"AddShow",
		strings.ToUpper("Post"),
		"/shows/",
		AddShow,
	},

	Route{
		"AddShowToCineplex",
		strings.ToUpper("Post"),
		"/cineplex/{cineplexId}/shows",
		AddShowToCineplex,
	},

	Route{
		"AddShowToMovie",
		strings.ToUpper("Post"),
		"/movies/{movieId}/shows",
		AddShowToMovie,
	},

	Route{
		"DeleteShow",
		strings.ToUpper("Delete"),
		"/shows/{showId}",
		DeleteShow,
	},

	Route{
		"DeleteShowList",
		strings.ToUpper("Delete"),
		"/shows/",
		DeleteShowList,
	},

	Route{
		"DeleteShowsForCineplex",
		strings.ToUpper("Delete"),
		"/cineplex/{cineplexId}/shows",
		DeleteShowsForCineplex,
	},

	Route{
		"DeleteShowsForMovie",
		strings.ToUpper("Delete"),
		"/movies/{movieId}/shows",
		DeleteShowsForMovie,
	},

	Route{
		"GetShowDetails",
		strings.ToUpper("Get"),
		"/shows/{showId}",
		GetShowDetails,
	},

	Route{
		"GetShows",
		strings.ToUpper("Get"),
		"/shows/",
		GetShows,
	},

	Route{
		"SetShowDetails",
		strings.ToUpper("Put"),
		"/shows/{showId}",
		SetShowDetails,
	},

	Route{
		"UpdateShowDetails",
		strings.ToUpper("Patch"),
		"/shows/{showId}",
		UpdateShowDetails,
	},

	Route{
		"AddReviewToMovie",
		strings.ToUpper("Post"),
		"/movies/{movieId}/reviews",
		AddReviewToMovie,
	},
}
